In [21]:
data = [ #Задание 1
[13, 25, 23, 34],
[45, 32, 44, 47],
[12, 33, 23, 95],
[13, 53, 34, 35],
]

In [26]:
def diagonal(data):
    sumMain = 0
    for i in range(len(data)):
        sumMain += data[i][i]
        
    return (sumMain)

In [27]:
diagonal (data)

103

In [30]:
data = [1, '5', 'abc', 20, '2'] #задание 2 

total_sum = 0

for i in data:
   try:
       total_sum += (int(i))**2
   except:
       print('Wrong number {}'.format(i))

print(total_sum)

Wrong number abc
430

In [43]:
class Rate: #задание 3
    def __init__(self, format='value'):
        self.format = format
    
    def exchange_rates(self):
        r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')
        return r.json()['Valute']
    def make_format(self, currency):
        response = self.exchange_rates()
        if currency in response:
            if self.format == 'full':
                return response[currency]
            
            if self.format == 'value':
                return response[currency]['Value']
        
        return 'Error'

In [44]:
import requests

In [48]:
sorted(Rate().exchange_rates().items(), key = lambda x: -x[1]['Value'] / x[1]['Nominal'])

[('XDR',
  {'ID': 'R01589',
   'NumCode': '960',
   'CharCode': 'XDR',
   'Nominal': 1,
   'Name': 'СДР (специальные права заимствования)',
   'Value': 90.0431,
   'Previous': 90.9974}),
 ('GBP',
  {'ID': 'R01035',
   'NumCode': '826',
   'CharCode': 'GBP',
   'Nominal': 1,
   'Name': 'Фунт стерлингов Соединенного королевства',
   'Value': 85.7452,
   'Previous': 86.6031}),
 ('EUR',
  {'ID': 'R01239',
   'NumCode': '978',
   'CharCode': 'EUR',
   'Nominal': 1,
   'Name': 'Евро',
   'Value': 73.361,
   'Previous': 74.0686}),
 ('USD',
  {'ID': 'R01235',
   'NumCode': '840',
   'CharCode': 'USD',
   'Nominal': 1,
   'Name': 'Доллар США',
   'Value': 64.6694,
   'Previous': 65.4201}),
 ('CHF',
  {'ID': 'R01775',
   'NumCode': '756',
   'CharCode': 'CHF',
   'Nominal': 1,
   'Name': 'Швейцарский франк',
   'Value': 64.5661,
   'Previous': 65.2504}),
 ('CAD',
  {'ID': 'R01350',
   'NumCode': '124',
   'CharCode': 'CAD',
   'Nominal': 1,
   'Name': 'Канадский доллар',
   'Value': 48.5615,
   'Previous': 49.2065}),
 ('SGD',
  {'ID': 'R01625',
   'NumCode': '702',
   'CharCode': 'SGD',
   'Nominal': 1,
   'Name': 'Сингапурский доллар',
   'Value': 47.843,
   'Previous': 48.3233}),
 ('AUD',
  {'ID': 'R01010',
   'NumCode': '036',
   'CharCode': 'AUD',
   'Nominal': 1,
   'Name': 'Австралийский доллар',
   'Value': 46.0187,
   'Previous': 46.3763}),
 ('AZN',
  {'ID': 'R01020A',
   'NumCode': '944',
   'CharCode': 'AZN',
   'Nominal': 1,
   'Name': 'Азербайджанский манат',
   'Value': 38.1193,
   'Previous': 38.5618}),
 ('BGN',
  {'ID': 'R01100',
   'NumCode': '975',
   'CharCode': 'BGN',
   'Nominal': 1,
   'Name': 'Болгарский лев',
   'Value': 37.5091,
   'Previous': 37.883}),
 ('BYN',
  {'ID': 'R01090B',
   'NumCode': '933',
   'CharCode': 'BYN',
   'Nominal': 1,
   'Name': 'Белорусский рубль',
   'Value': 30.5982,
   'Previous': 30.7425}),
 ('TMT',
  {'ID': 'R01710A',
   'NumCode': '934',
   'CharCode': 'TMT',
   'Nominal': 1,
   'Name': 'Новый туркменский манат',
   'Value': 18.5034,
   'Previous': 18.7182}),
 ('PLN',
  {'ID': 'R01565',
   'NumCode': '985',
   'CharCode': 'PLN',
   'Nominal': 1,
   'Name': 'Польский злотый',
   'Value': 17.0632,
   'Previous': 17.2199}),
 ('BRL',
  {'ID': 'R01115',
   'NumCode': '986',
   'CharCode': 'BRL',
   'Nominal': 1,
   'Name': 'Бразильский реал',
   'Value': 16.9411,
   'Previous': 17.0276}),
 ('RON',
  {'ID': 'R01585F',
   'NumCode': '946',
   'CharCode': 'RON',
   'Nominal': 1,
   'Name': 'Румынский лей',
   'Value': 15.4335,
   'Previous': 15.5729}),
 ('TRY',
  {'ID': 'R01700J',
   'NumCode': '949',
   'CharCode': 'TRY',
   'Nominal': 1,
   'Name': 'Турецкая лира',
   'Value': 11.8329,
   'Previous': 11.9556}),
 ('DKK',
  {'ID': 'R01215',
   'NumCode': '208',
   'CharCode': 'DKK',
   'Nominal': 10,
   'Name': 'Датских крон',
   'Value': 98.3057,
   'Previous': 99.2808}),
 ('CNY',
  {'ID': 'R01375',
   'NumCode': '156',
   'CharCode': 'CNY',
   'Nominal': 10,
   'Name': 'Китайских юаней',
   'Value': 96.3504,
   'Previous': 97.4558}),
 ('HKD',
  {'ID': 'R01200',
   'NumCode': '344',
   'CharCode': 'HKD',
   'Nominal': 10,
   'Name': 'Гонконгских долларов',
   'Value': 82.3814,
   'Previous': 83.3409}),
 ('NOK',
  {'ID': 'R01535',
   'NumCode': '578',
   'CharCode': 'NOK',
   'Nominal': 10,
   'Name': 'Норвежских крон',
   'Value': 75.8185,
   'Previous': 76.5738}),
 ('SEK',
  {'ID': 'R01770',
   'NumCode': '752',
   'CharCode': 'SEK',
   'Nominal': 10,
   'Name': 'Шведских крон',
   'Value': 70.0568,
   'Previous': 70.6305}),
 ('TJS',
  {'ID': 'R01670',
   'NumCode': '972',
   'CharCode': 'TJS',
   'Nominal': 10,
   'Name': 'Таджикских сомони',
   'Value': 68.542,
   'Previous': 69.3193}),
 ('ZAR',
  {'ID': 'R01810',
   'NumCode': '710',
   'CharCode': 'ZAR',
   'Nominal': 10,
   'Name': 'Южноафриканских рэндов',
   'Value': 44.8048,
   'Previous': 45.3063}),
 ('MDL',
  {'ID': 'R01500',
   'NumCode': '498',
   'CharCode': 'MDL',
   'Nominal': 10,
   'Name': 'Молдавских леев',
   'Value': 37.5439,
   'Previous': 37.9797}),
 ('CZK',
  {'ID': 'R01760',
   'NumCode': '203',
   'CharCode': 'CZK',
   'Nominal': 10,
   'Name': 'Чешских крон',
   'Value': 28.6148,
   'Previous': 28.8703}),
 ('UAH',
  {'ID': 'R01720',
   'NumCode': '980',
   'CharCode': 'UAH',
   'Nominal': 10,
   'Name': 'Украинских гривен',
   'Value': 23.8206,
   'Previous': 24.1661}),
 ('INR',
  {'ID': 'R01270',
   'NumCode': '356',
   'CharCode': 'INR',
   'Nominal': 100,
   'Name': 'Индийских рупий',
   'Value': 94.3376,
   'Previous': 94.7122}),
 ('KGS',
  {'ID': 'R01370',
   'NumCode': '417',
   'CharCode': 'KGS',
   'Nominal': 100,
   'Name': 'Киргизских сомов',
   'Value': 92.716,
   'Previous': 93.7251}),
 ('JPY',
  {'ID': 'R01820',
   'NumCode': '392',
   'CharCode': 'JPY',
   'Nominal': 100,
   'Name': 'Японских иен',
   'Value': 57.9917,
   'Previous': 58.5651}),
 ('HUF',
  {'ID': 'R01135',
   'NumCode': '348',
   'CharCode': 'HUF',
   'Nominal': 100,
   'Name': 'Венгерских форинтов',
   'Value': 23.34,
   'Previous': 23.568}),
 ('KZT',
  {'ID': 'R01335',
   'NumCode': '398',
   'CharCode': 'KZT',
   'Nominal': 100,
   'Name': 'Казахстанских тенге',
   'Value': 17.1865,
   'Previous': 17.2485}),
 ('AMD',
  {'ID': 'R01060',
   'NumCode': '051',
   'CharCode': 'AMD',
   'Nominal': 100,
   'Name': 'Армянских драмов',
   'Value': 13.3037,
   'Previous': 13.4264}),
 ('KRW',
  {'ID': 'R01815',
   'NumCode': '410',
   'CharCode': 'KRW',
   'Nominal': 1000,
   'Name': 'Вон Республики Корея',
   'Value': 57.0795,
   'Previous': 57.5732}),
 ('UZS',
  {'ID': 'R01717',
   'NumCode': '860',
   'CharCode': 'UZS',
   'Nominal': 10000,
   'Name': 'Узбекских сумов',
   'Value': 77.2486,
   'Previous': 78.1457})]